### ISSUE TITLE
Photo can't be centered using the code in `index.md`

### ISSUE THREAD

**Issue by luliudata** [pennchildlanglab/pennchildlanglab.github.io#1]
Hi I'm currently following your website as a template to set up my personal website (awesome tutorial on Youtube by the way, thanks for that!)

The issue I encountered is in file `index.md`:
```
  <p align="center">
      <img src= "images/lablogo.png" width="200" height="200" align="middle"/>
  </p>
```

I used the same code for my profile photo: https://github.com/luliudata/luliudata.github.io/blob/master/index.md, the photo is centred in the markdown file, but it's not centred on the webpage: https://luliudata.github.io/, just wondering any chance you know what I'm missing here? Thanks in advance.

**Comment by kschuler** [comment]
Hi Lu,

You can do it by enclosing your image in the <center> tag, though that might not always work in all browsers going forward:

<center>
	<img src= "images/lablogo.png" width="200" height="200" >
</center>

Or, if you want to pass css style elements directly in html you need to use the style attribute in your enclosing <p> tag:

<p style=“text-align:center;”>
	<img src= "images/lablogo.png" width="200" height="200" >
</p>

Hope that helps!

Yours, Katie

**Comment by luliudata** [comment]
Hi Katie, thanks for the reply. I'll give it a try, thank you :)
